#' Show signature activity from the output generated by \code{AddSigActivity}
#'
#' @param list.of.sig.activity A list of contributing signature activity
#'   information for multiple spectra. See the return value of
#'   \code{\link{AddSigActivity}} for more details.
#' 
#' @param output.dir The directory to save the results. Create
#'   this directory if it does not exist.
#'   
#' @param base.filename Optional. \code{base.filename} will be appended to the start
#' of the names of files generated inside \code{output.dir}.
#'   
#' @param plot.all.samples.in.one.pdf Whether to plot all the signature activity information
#'   within one PDF. Default is TRUE. If FALSE, then plot one PDF for each sample.
#' 
#' @param plot.exposure.proportion Whether to plot exposure proportions rather
#'   than counts.
#'   
#' @param mfrow A vector of the form \code{c(nr, nc)}. Subsequent figures will
#'   be drawn in an \code{nr}-by-\code{nc} array on the device by rows.
#'   
#' @param mar A numerical vector of the form \code{c(bottom, left, top, right)}
#'   which gives the number of lines of margin to be specified on the four sides
#'   of the plot.
#'
#' @param oma A vector of the form \code{c(bottom, left, top, right)} giving the
#'   size of the outer margins in lines of text.
#' 
#' @param ... Other arguments passed to \code{\link[ICAMS]{PlotCatalogToPdf}}.
#' 
#' @keywords internal
#'
#' @examples
#' \dontrun{
#' spectra <- PCAWG7::spectra$PCAWG$SBS96[, 1:2, drop = FALSE]
#' exposure <- PCAWG7::exposure$PCAWG$SBS96[, 1:2, drop = FALSE]
#' sigs <- cosmicsig::COSMIC_v3.2$signature$GRCh37
#' sigs.prop <- ExposureProportions(mutation.type = "SBS96", 
#'                                  cancer.type = "Biliary-AdenoCA")
#' retval <- AddSigActivity(spectra, exposure, sigs, sigs.prop)
#' ShowSigActivity(retval, output.dir = file.path(tempdir(), "SBS96"), 
#'                 base.filename = "Biliary-AdenoCA")
#'}                
ShowSigActivity <- function(list.of.sig.activity,
                            output.dir,
                            base.filename = NULL,
                            plot.all.samples.in.one.pdf = TRUE, 
                            plot.exposure.proportion = FALSE,
                            mfrow = c(2, 1),
                            mar  = c(6, 4, 3, 2),
                            oma  = c(3, 2, 0, 2),
                            ...) {
  if (!dir.exists(output.dir)) {
    dir.create(output.dir, recursive = TRUE)
  }
  
  mut.type <- GetMutationType(list.of.sig.activity[[1]][[1]])
  
  WriteDistances(list.of.sig.activity = list.of.sig.activity, 
                 output.dir = output.dir, 
                 base.filename = base.filename,
                 mutation.type = mut.type)
  PlotSigActivityToPdf(list.of.sig.activity = list.of.sig.activity, 
                       output.dir = output.dir,
                       base.filename = base.filename,
                       mutation.type = mut.type,
                       plot.all.samples.in.one.pdf = plot.all.samples.in.one.pdf, 
                       ... = ...)
  ShowExposure(list.of.sig.activity = list.of.sig.activity, 
               output.dir = output.dir,
               base.filename = base.filename,
               mutation.type = mut.type,
               plot.exposure.proportion = plot.exposure.proportion,
               mfrow = mfrow,
               mar = mar,
               oma = oma)
  
}

#' Show signature exposure from the output generated by \code{AddSigActivity}
#'
#' @inheritParams ShowSigActivity
#' 
#' @param mutation.type The mutation type of the mutational spectrum.
#' 
#' @keywords internal
ShowExposure <- function(list.of.sig.activity, output.dir, base.filename,
                         mutation.type,
                         plot.exposure.proportion = FALSE,
                         mfrow = c(2, 1),
                         mar  = c(6, 4, 3, 2),
                         oma  = c(3, 2, 0, 2)) {
  # Retrieve the exposure information
  exposure.info <- lapply(list.of.sig.activity, FUN = function(x) {
    spect <- x$original.spect
    return(attr(spect, "exposure"))
  })
  
  exposure <- do.call(cbind, exposure.info)
  
  # Remove rows with zero exposure
  exposure <- exposure[rowSums(exposure) > 0, , drop = FALSE]
  
  if (is.null(base.filename)) {
    file.name.append <- mutation.type
  } else {
    file.name.append <- paste0(base.filename, ".", mutation.type)
  }
  
  if (isTRUE(plot.exposure.proportion)) {
    if (is.null(base.filename)) {
      output.file <- 
        file.path(output.dir, paste0(file.name.append, ".all.samples.exposure.props.pdf"))
    } else {
      output.file <- 
        file.path(output.dir, paste0(file.name.append, ".all.samples.exposure.props.pdf"))
    }
    
  } else {
    output.file <- 
      file.path(output.dir, paste0(file.name.append, ".all.samples.exposure.counts.pdf"))
  }
  
  mSigTools::plot_exposure_to_pdf(exposure = exposure, 
                                  file = output.file,
                                  plot.proportion = plot.exposure.proportion,
                                  mfrow = mfrow,
                                  mar = mar,
                                  oma = oma)
  
}

#' Write distances from the output generated by \code{AddSigActivity}
#'
#' @inheritParams ShowSigActivity
#' 
#' @param mutation.type The mutation type of the mutational spectrum.
#'
#' @keywords internal
WriteDistances <- 
  function(list.of.sig.activity, output.dir, base.filename, mutation.type) {
  if (!dir.exists(output.dir)) {
    dir.create(output.dir)
  }
  
  # Retrieve the distances information
  distances.info <- lapply(list.of.sig.activity, FUN = function(x) {
    distances <- x$distances
    values <- matrix(distances$proposed.assignment, ncol = nrow(distances))
    colnames(values) <- distances$method
    return(as.data.frame(values))
  })
  
  retval <- do.call(dplyr::bind_rows, distances.info)
  rownames(retval) <- names(list.of.sig.activity)
  
  if (is.null(base.filename)) {
    file.name.append <- mutation.type
  } else {
    file.name.append <- paste0(base.filename, ".", mutation.type)
  }
  
  output.file <- 
    file.path(output.dir, paste0(file.name.append, ".all.samples.distances.csv"))
  write.csv(retval, file = output.file)
  
}


